(define (make-monitored func)
  (define counter 0)
  (define (mf cmd)
    (cond ((eq? cmd 'how-many-calls?) counter)
          ((eq? cmd 'reset-count) (set! counter 0))
          (else (begin (set! counter (+ counter 1))
                       (func cmd))))
  )
  mf)
