(define (rand-update x) (+ x 1))
(define (make-rand)
  (define x 0)
  (define (dispatch cmd)
    (cond ((eq? cmd 'generate)
           (set! x (rand-update x))
           x)
          ((eq? cmd 'reset)
           (lambda (new-x) (set! x new-x)))
          (else ((error "Unknown Message - " cmd)))))
  dispatch)
